ALTER TABLE avaliacoes
    ADD COLUMN IF NOT EXISTS tipo TEXT NOT NULL DEFAULT 'PROVA',
    ADD COLUMN IF NOT EXISTS peso NUMERIC(5,2) NOT NULL DEFAULT 1;

ALTER TABLE avaliacoes ALTER COLUMN tipo DROP DEFAULT;
ALTER TABLE avaliacoes ALTER COLUMN peso DROP DEFAULT;

ALTER TABLE aval_questoes ALTER COLUMN correta DROP NOT NULL;
